# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

pod 'AFNetworking', '~> 2.5'

target 'PixoThreeTabViewXcodeProject' do

end

target 'PixoThreeTabViewXcodeProjectTests' do

end

